import { StyleSheet } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  _header_main: {
    backgroundColor: "#1EA3C8",
    paddingHorizontal: 20,
    paddingVertical: hp("1.5%"),
  },
  _header_title_main: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  _header_back_icon_main: {
    flexDirection: "row",
    alignItems: "center",
  },
  _back_btn: {
    width: 30,
    height: 30,
    borderRadius: 30 / 2,
    alignItems: "center",
    justifyContent: "center",
  },
  _header_heading: {
    color: "#fff",
    fontFamily: "Roboto-Bold",
    fontSize: 16,
  },
  _next_btn: {
    backgroundColor: "#1EA3C8",
    width: "90%",
    height: hp("7%"),
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginHorizontal: 20,
    borderRadius: 5,
    marginTop: hp("3%"),
  },
  _next_btn_text: {
    color: "#fff",
    fontFamily: "Roboto-Bold",
    fontSize: 16,
  },
  _card_main: {
    backgroundColor: "#F1EFEF",
    padding: 20,
    marginBottom: 15,
  },
  _card_header_main: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  _card_header_title: {
    color: "#000",
    fontFamily: "Roboto-Regular",
    fontSize: 12,
    marginLeft: 5,
  },
  _selected_item_main: {
    marginTop: hp("2%"),
  },
  _selected_item_heading: {
    color: "#000",
    fontFamily: "Roboto-Regular",
    fontSize: 12,
  },
  _selected_item_size_main: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  _selected_item_size_title: {
    color: "#656565",
    fontFamily: "Roboto-Regular",
    fontSize: 12,
  },
  _selected_item_size_price: {
    color: "#000",
    fontFamily: "Roboto-Regular",
    fontSize: 12,
  },
  _line: {
    backgroundColor: "#CBCBCB",
    height: 1,
    flex: 1,
    marginVertical: hp("2%"),
  },
  _discount: {
    color: "#717171",
    fontFamily: "Roboto-Regular",
    fontSize: 12,
  },
  _total_amount: {
    color: "#000",
    fontFamily: "Roboto-Bold",
    fontSize: 12,
  },
  _input_main: {
    flexDirection: "row",
    backgroundColor: "white",
    height: hp("6%"),
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    marginTop: hp("2%"),
    elevation: 2,
  },
  _input: {
    color: "#717171",
    fontFamily: "Roboto-Bold",
    fontSize: 12,
    width: "100%",
  },
  _heading: {
    color: "#000",
    fontFamily: "Roboto-Bold",
    fontSize: 17,
    marginHorizontal: 20,
    marginTop: hp("2%"),
    marginBottom: hp("3%"),
  },
  _payment_method_main: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "#F1F1F1",
    marginHorizontal: 20,
    paddingVertical: 15,
  },
  _payment_method_title_main: {
    flexDirection: "row",
    alignItems: "center",
  },
  _payment_method_title: {
    color: "#000",
    fontFamily: "Roboto-Bold",
    fontSize: 12,
    marginLeft: 10,
  },
  _payment_method_title_selected: {
    color: "#545454",
    fontFamily: "Roboto-Bold",
    fontSize: 12,
    marginLeft: 10,
  },
  _payment_method_selected: {
    width: 14,
    height: 14,
    borderWidth: 1,
    borderColor: "#707070",
    borderRadius: 14 / 2,
    backgroundColor: "#fff",
    padding: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  _payment_method_selected_bg: {
    backgroundColor: "#1EA3C8",
    width: 10,
    height: 10,
    borderRadius: 10 / 2,
  },
  _payment_method_withoutselected_bg: {
    backgroundColor: "#fff",
    width: 10,
    height: 10,
    borderRadius: 10 / 2,
  },
  _card_payment_main: {
    marginHorizontal: 20,
    marginBottom: 20,
  },
  _card_input_heading: {
    color: "#000",
    fontFamily: "Roboto-Bold",
    fontSize: 12,
    marginTop: hp("3%"),
  },
  _code_main: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  _code: {
    width: "45%",
  },
});
