import { StyleSheet } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "white",
  },
  _image: {
    flex: 1,
    resizeMode: "cover",
    height: hp("100%"),
    width: wp("100%"),
    paddingHorizontal: 20,
  },
  _heading: {
    color: "#000",
    fontFamily: "Roboto-Regular",
    fontSize: 29,
    marginTop: hp("5%"),
    textAlign: "center",
  },
  _header_main: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: hp("5%"),
  },
  _header_heading: {
    fontFamily: "Roboto-Regular",
    color: "#fff",
    fontSize: 16,
    marginLeft: 5,
  },
  _input_main: {
    width: "100%",
    height: hp("7%"),
    marginTop: hp("5%"),
    backgroundColor: "#E2E2E2",
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  _input: {
    width: "90%",
    fontFamily: "Roboto-Regular",
    fontSize: 13,
    padding: 0,
    margin: 0,
    color: "#193628",
  },
  _logo_main: {
    height: hp("20%"),
    marginTop: hp("10%"),
  },
  _forgot_password: {
    fontFamily: "Roboto-Regular",
    fontSize: 13,
    color: "#000",
    alignSelf: "flex-end",
    marginTop: hp("3%"),
  },
  button: {
    height: hp("6%"),
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    alignSelf: "center",
    backgroundColor: "#18A6CC",
    marginTop: hp("4%"),
  },
  btn_text: {
    color: "#fff",
    fontSize: 16,
    fontFamily: "Roboto-Bold",
  },
  _service_provider: {
    height: hp("6%"),
    alignItems: "center",
    justifyContent: "center",
    width: "65%",
    alignSelf: "center",
    marginTop: hp("4%"),
    borderWidth: 1,
    borderColor: "#26A29D",
  },
  _service_provider_text: {
    color: "#000",
    fontSize: 16,
    fontFamily: "Roboto-Regular",
  },
  _signup_main: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginTop: hp("2%"),
    marginBottom: hp("3%"),
  },
  _account: {
    color: "#193628",
    fontSize: 16,
    fontFamily: "Roboto-Regular",
  },
  _signup: {
    color: "#5EBDD7",
    fontSize: 18,
    fontFamily: "Roboto-Bold",
    marginLeft: 2,
  },
});
